FROM golang:1.24-alpine3.22 AS builder

WORKDIR /usr/src/ksu

# зависимости
COPY ./go.mod ./go.sum ./
RUN go mod download

# исходники + билд бинарника
COPY ./cmd/task ./cmd/task
COPY ./pkg ./pkg 
COPY ./internal ./internal
RUN go build -o /usr/local/app-task ./cmd/task/main.go

###
FROM alpine:3.22 AS runner

COPY --from=builder /usr/local/app-task /
COPY ./config/config.yaml /config.yaml

ENTRYPOINT [ "/app-task" ]