server:
  read_timeout: "5s"
  write_timeout: "10s"
  read_header_timeout: "2s"
  idle_timeout: "30s"

logger:
  handler: "json"
  level: "debug"

app:
  semaphore: 16

clickhouse:
  address: clickhouse:9000
  username: ksu
  password: secret
  try_connection_perod: "3s"
  connection_attempts: 5
  butch_size: 10
  butch_inteval: "1m"