server:
  read_timeout: "5s"
  write_timeout: "10s"
  read_header_timeout: "2s"
  idle_timeout: "30s"

logger:
  handler: json
  level: debug
  output_internal: false

app:
  semaphore: 16

clickhouse:
  address: clickhouse:9000
  username: ksu
  password: secret
  try_connection_perod: "3s"
  connection_attempts: 5
  batch_size: 10
  batch_inteval: "1m"

storage:
  type: postgres # internal | postgres
  host: db
  port: 5432
  user: app
  password: 123
  name: app_db
  ssl_mode: disable
  need_migrate: true
  migaret_src: file:///migrate
  
